Support passing file / folder exclude options
unlight/sublime-import-helper pull request #64
Opened 2019-05-18 19:29 UTC by p-mcgowan

RE: https://github.com/unlight/esm-exports/pull/14

This would prevent the plugin from crashing when a large project-ignored folder is processed. Currently, I have manually edited the packages in my sublime config in order to retain imports in that project file, but naturally that means any updates would likely break it.

Assuming the other PR is merged in and the package published, `package.json` would need a version bump (3.0.4+ possibly).

2019-05-20 09:05 UTC, unlight commented
Thanks for PR.
Are already using this in work? How long and what is your OS?

2019-05-21 21:35 UTC, unlight requested changes

2019-05-21 21:35 UTC, unlight commented on utils.py
> +        data[folder] = result
TypeError: unhashable type: 'dict'

folder is object here, why we need change to array to dictionary?

2019-05-22 19:34 UTC, merged

2019-05-22 19:35 UTC, unlight commented on utils.py
> +        data[folder] = result
I have to modify it, see commit https://github.com/unlight/sublime-import-helper/commit/b05baf6cd4d53fdec38c1fa4102f2773b8172ea9

2019-05-23 13:21 UTC, p-mcgowan commented
Hey - sorry, missed the notification, thanks for fixing up my bug(s)!

I've been using the plugin for about 8 months now (at work and personal projects). I'm running Ubuntu 18.04 Linux.

2019-05-23 14:11 UTC, unlight commented
Hi @p-mcgowan I pushed your changes with some fixes to `master` can you backup your version and try my from [master](https://github.com/unlight/sublime-import-helper/archive/master.zip)

> Just tried to update from Package Control - still reads 2.1.0
Release tag is not yet created

2019-05-24 09:57 UTC, p-mcgowan commented
Perfect - works like a charm